[package]
name = "bux-modules"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bux-core = { path = "../bux-core" }
anyhow.workspace = true
serde.workspace = true

