[package]
name = "bux-globaltool"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "bux-globaltool"
path = "src/main.rs"

[dependencies]
bux-cli = { path = "../bux-cli" }

